# Generated by Django 4.2.11 on 2024-04-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='computer.computerspecification'),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='computer.computerbrands'),
        ),
    ]
